.\" Hand written
.\"
.TH "FILEDUPS" "1" "2020-02-26" "" "General Commands Manual"
.hy
.SH NAME
.PP
\f[B]dname_grep\f[] - generates a list of duplicated files in a dir
entered by the user.
.SH SYNOPSIS
.PP
\f[B]dname_grep\f[] [\f[B]-h\f[]] [\f[B]--help\f[]]
.PP
\f[B]dname_grep\f[] [\f[B]-v\f[]] [\f[B]--version\f[]]
.PP
\f[B]dname_grep\f[] [options] \f[I][dir to search]\f[]
.SH DESCRIPTION
.PP
\f[B]dname_grep\f[] searches the user input directory for duplicated
files and lists them in a file, \f[I]dups.lst\f[] in a format useable
by \f[B]procdups\f[] for action chosen interactively by the user. The
output file, \f[I]dups.lst\f[] is written to the current directory.
The default search dir is the user's current dir.
.PP
The program removes from consideration as many files as it can determine
are unique, before running \f[B]md5sum\f[] checks to test for equality.
The \f[B]md5sum\f[] checks are run against the lesser of the first
4096 bytes of the file, or it's size in bytes. The extent of the
\f[B]md5sum\f[] check is optionally changeable.
.PP
Under no circumstances will a file of zero length ever be considered
for testing as a duplicate. It is also possible to exclude named files
or paths from consideration by entering \f[B]grep\f[] patterns into
the programs config file, see \f[B]FILES\f[] below.
.PP
.SH OPTIONS
.TP
.B -h, --help
Displays this help message then quits.

.TP
.B -v, --version
Displays this program's version number then quits.

.TP
.B -p, --pages
Selects the number of blocks of 4096 bytes at the front of the file to
use to generate the \f[B]md5sum\f[]. By default this is 1 page only,
4096 bytes. Any number at all may be entered, but numbers less than 1
will cause the the entire file content to be used to calculate the sum.
This will be very time consuming for large files such as video files,
and is likely unnecessary.

.SH FILES
.PP
See \f[B]$HOME/.config/filedups/dname_grep.cfg

.SH SEE ALSO
\f[B]procdups\f[](1)
